import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the dark mode
export interface DarkModeState {
  mode: 'white' | 'black';
}

const initialState: DarkModeState = {
  mode: JSON.parse(localStorage.getItem("darkMode")!) || 'white', 
};


export const darkModeSlice = createSlice({
  name: 'darkMode', // The name of the slice
  initialState, // Initial state defined above
  reducers: {
    toggleDarkMode: (state) => {
   
      state.mode = state.mode === 'black' ? 'white' : 'black';
      localStorage.setItem("darkMode", JSON.stringify(state.mode));
    },
  },
});

// Export the actions generated by the slice
export const { toggleDarkMode } = darkModeSlice.actions;

// Export the reducer function for use in the Redux store
export default darkModeSlice.reducer;
